from exceptions import Exception

class YaExiste(Exception):
    pass

